# -*- coding: utf-8 -*-
"""test_main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hF5IQEMJ_V2GBFWjsxRvCAb-bo3mbwt2
"""

import main
from transformers import pipeline

def test():
    assert main.for_test == 'Success'

def test_model():
    assert main.model_ckpt == "papluca/xlm-roberta-base-language-detection"